### ISSUE TITLE
Can be set to the default insert mode

### ISSUE THREAD

**Issue by nick357** [DCsunset/vscode-modal-editor#1]
默认是normal-mode，我想在特定场景下，启动为insert-mode。按esc后在进入到normal模式

**Comment by nightscape** [comment]
@nick357 can you run that through Google Translate or something?

**Comment by nick357** [comment]
@nightscape  sorray
my question is
The default is normal-mode, I want to start as insert-mode in a specific scenario. Press esc to enter normal mode

**Comment by DCsunset** [comment]
Hello @nick357, the defaultMode config has been added in v1.5.2.

**Comment by nick357** [comment]
@DCsunset Found. Thank you.
