### ISSUE TITLE
Configuration not updated after loading keybindings from file or URI

### ISSUE THREAD

**Issue by endereyewxy** [DCsunset/vscode-modal-editor#10]
It seems that loading keybinds from local file or URI does not correctly update the application's state and configuration afterwards. Currently the only working way to update the keybindings is through "Import from preset directory".

I think this is caused by a bug at [here](https://github.com/DCsunset/vscode-modal-editor/blob/main/src/commands.ts#L85), where the keybindings are actually loaded, but not updated.

Potentially causing #9 .

**Comment by DCsunset** [comment]
That's a good observation. I have fixed the bug in the latest version. Could you verify that it works at your side as well?

**Comment by endereyewxy** [comment]
Yes it works now. Thank you.
