### ISSUE TITLE
How to change into insert mode without clearing selection?

### ISSUE THREAD

**Issue by digitalmaster** [DCsunset/vscode-modal-editor#15]
For some reason anytime I toggle insert mode it clears the current selection. Is there a way to prevent that?

**Comment by digitalmaster** [comment]
Oh nvm looks like this is intentional:
https://github.com/DCsunset/vscode-modal-editor/blob/c3a4469fd8fcc788ffb112e9ae96b168606ee332/src/commands.ts#L175-L177

The use case is I want to issue a visual selection command and then perform an wrapping insert action (ie., wrapping selection with brackets).

I've tested that removing this line does the trick for me on my build. I'm curious what the use case for clearing the selection is tho? 🤔 

We could make it a setting (defaulting to current behavior)?

**Comment by DCsunset** [comment]
Yes that was intentional originally. Because any insertion under active selection in VSCode will replace the selection with the inserted text.

But it does make sense to let the user decide whether to clear to selection. I'll add a setting shortly to address this issue..

**Comment by digitalmaster** [comment]
Gotcha. Makes sense.

> Because any insertion under active selection in VSCode will replace the selection with the inserted text.

This is true. However, replacement only happens once you've started typing characters not on the action to go back to insert mode (since that's not a thing).

I wonder if the default behavior should be to not clear selection? For [reference](https://github.com/johtela/vscode-modaledit/blob/2c83f43c9fcff646622354e8db5c4f06f1d43adf/src/commands.ts#L313-L316), ModalEdit also doesn't clear it for the same reason.

**Comment by DCsunset** [comment]
Yes. I think I can probably remove the `clearSelections` command. Users can call it by themselves if they want.

**Comment by DCsunset** [comment]
This has been implemented in the latest commit. Feel free to try it if you have time.

**Comment by digitalmaster** [comment]
Nice!.

Just pull/built your changes. However your backwards compatibility change essentially makes it so that I can't use "modalEditor.setInsertMode".. So trying to figure how to use "modalEditor.setInsertMode("insert")".. Currently getting the following error:
`command 'modalEditor.setMode('insert')' not found`

**Comment by DCsunset** [comment]
You should pass arguments using `args` in ComplexCommand instead of putting it in the command name

**Comment by digitalmaster** [comment]
Ahh.. makes sense. Thanks 🙌🏽🙌🏽

**Comment by digitalmaster** [comment]
Yea, that did the trick for me. I essentially just created a small object with the search change into insert mode using the right helper:
```js
const Mode = {
  Insert: { command: "modalEditor.setMode", args: "insert" }
};
```

Gonna go ahead and close this issue for now. Still think having two different behaviors for these commands will create confusion for others. Adding a setting that defaults to on to main backward compatibility seems like the better way to do this. 

Thanks again for iterating on this so quickly. I've officially migrated over to using this plugin 🎉
