### ISSUE TITLE
Plans to have a different cursor between insert and command mode?

### ISSUE THREAD

**Issue by ggayan** [DCsunset/vscode-modal-editor#2]
First of all, thanks for working on this extension. I love that you are providing a preset for helix key mappings;

I noticed that there is no visual difference on the buffer cursor when switching between normal mode and command mode; Is this expected?

It would be nice to have something similar to what the dance or vim extensions do on vscode.

**Comment by DCsunset** [comment]
Hi, that's a good suggestion. I'll probably add it in a few days when I'm free.

**Comment by DCsunset** [comment]
Hi, I've updated the docs about [settings](https://github.com/DCsunset/vscode-modal-editor#settings).
You can customize the cursor styles and status texts as you want.
