### ISSUE TITLE
Key mapping dependent on editor language

### ISSUE THREAD

**Issue by anthonyjclark** [DCsunset/vscode-modal-editor#6]
I would like to have language-specific mappings. For example:

```js
		"o": recordChange(
			{ command: ["editor.action.insertLineAfter", "modalEditor.setInsertMode"], when: "editorLangId != markdown" },
			{ command: ["cursorLineEnd", "markdown.extension.onEnterKey"], when: "editorLangId == markdown"}
		),
```

With only the first option, I do not get automatic bullet list continuation in markdown files. 

I could put the "o" key in `keybindings.json` to make this work, but that would make managing my key bindings more complicated.

I might look into adding `editorLangId` to `_ctx` but I thought I'd ask you first if such a PR would be welcomed.

**Comment by DCsunset** [comment]
Sure, I think it's reasonable to add it to `_ctx` as it may be a commonly used property. It would be great if you'd like submit a PR for this.

**Comment by anthonyjclark** [comment]
I will not get to it for a while. I'll post an update here when I start working on it.
